name: Git Integration

on: workflow_dispatch

jobs:
  git-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files from repo
        run: ls -R
