name: Version Check

on: workflow_dispatch

jobs:
  version-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner version
        run: |
          uname -a
          git --version
          java -version
